# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LottieExtensionDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LottieExtensionDemo
pod 'lottie-ios_Oc'

  target 'LottieExtensionDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LottieExtensionDemoUITests' do
    # Pods for testing
  end

end
